Test: CheckMisa
Target: verilator_target
Waiting for OpenOCD to start up...
--------------------------------[ Traceback ]---------------------------------
Traceback (most recent call last):
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 1389, in run
    self.classSetup()
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 1445, in classSetup
    BaseTest.classSetup(self)
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 1352, in classSetup
    self.target_process = self.target.create()
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/targets/RISC-V/verilator_target.py", line 38, in create
    return testlib.Openocd(server_cmd=f"openocd -f {self.openocd_config_path}")
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 385, in __init__
    hello_string = self.command(
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 461, in command
    self.openocd_cli.expect(rb"(.*)\x1a")
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 343, in expect
    return self.expect_list(compiled_pattern_list,
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7ae7ae3f5ea0>
command: /usr/bin/nc
args: ['/usr/bin/nc', 'localhost', 'None']
buffer (last 100 chars): b''
before (last 100 chars): b'nc: port number invalid: None\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 1
flag_eof: True
pid: 27083
child_fd: 11
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'(.*)\\x1a')
-------------------------------[ End of logs ]--------------------------------
Result: exception
Logfile: logs/20250603-135245-verilator_target-CheckMisa.log
Reproduce: ./gdbserver.py targets/RISC-V/verilator_target.py CheckMisa
Time elapsed: 2.86s
